import { RouterState } from "connected-react-router";
import IRequestingState from "stores/requesting/models/IRequestingState";
import IErrorState from "stores/error/models/IErrorState";
import IToastsState from "stores/toasts/models/IToastsState";
import IServiceCatalogState from "stores/service-catalog/models/IServiceCatalogState";
import IServiceCatalogCategoryState from "stores/service-catalog-category/models/IServiceCatalogCategoryState";
import IEmployeeState from "stores/employee/models/IEmployeeState";
import IBrandState from "stores/brand/models/IBrandState";
import IBondTypeState from "stores/bond-type/models/IBondTypeState";
import ILetterTypeState from "stores/bond-type/models/IBondTypeState";
import ILanguageState from "stores/language/models/ILanguageState";
import IBankState from "stores/bank/models/IBankState";
import IBondIssuerState from "stores/bond-issuer/models/IBondIssuerState";
import IDocumentTypeState from "stores/document-type/models/IDocumentTypeState";
import IIndustryClassState from "stores/industry-class/models/IIndustryClassState";
import IPresalesSupportState from "stores/presales-support/models/IPresalesSupportState";
import {
  ICustomerTransferState,
  IHistoryState,
  IDataFunnelState,
  IDataFunnelCustomerState,
  IValueState,
} from "stores/customer-transfer/models/ICustomerTransferState";
import ICustomerState from "stores/customer/models/ICustomerState";
import IServiceOwnerState from "stores/service-owner/models/IServiceOwnerState";
import ISubBrandState from "stores/brand-sub/models/ISubBrandState";
import IFunnelState from "stores/funnel/models/IFunnelState";
import ICustomerPICState from "stores/customer-pic/models/ICustomerPICState";
import IProductServiceState from "stores/funnel-product-service/models/IProductServiceState";
import IFunnelActivityState from "stores/funnel-activity/models/IFunnelActivityState";
import IAttachmentState from "stores/attachment/models/IAttachmentState";
import IAttachmentVersionsState from "stores/attachment-versions/models/IAttachmentVersionsState";
import ICustomerToFunnelState from "stores/customer/models/ICustomerToFunnelState";
import IActivityTypeState from "stores/activity-type/models/IActivityTypeState";
import ISidebarContainerState from "stores/sidebar-containers/models/ISidebarContainerState";
import IMeetingRequestState from "stores/meeting-request/models/IMeetingRequestState";
import IBrandTypeState from "stores/brand-model/models/IBrandTypeState";
import IMeetingMomItemState from "stores/meeting-mom-items/models/IMeetingMomItemState";
import IMeetingMomState from "stores/meeting-mom/models/IMeetingMomState";
import IFunnelServiceCatalogState from "stores/funnel-service-catalog/models/IFunnelServiceCatalogState";
import IBoqState from "stores/boq/models/IBoqState";
import IInsuranceModelState from "stores/insurance/models/IInsuranceState";
import IPostsalesSupportState from "stores/postsales-support/models/IPostsalesSupportState";
import IPOCState from "stores/funnel-poc-request/models/IPOCState";
import IFunnelStatusState from "stores/funnel-status/models/IFunnleStatusState";
import IUserState from "stores/users/models/IUserState";
import ISupportRoleState from "stores/support-role/models/ISupportRoleState";
import IFunnelSupportTeamState from "stores/funnel-support-teams/models/IFunnelSupportTeamState";
import IBankGaransiState from "stores/bank-garansi/models/IBankGaransiState";
import IReqDedicatedResourceState from "stores/funnel-dedicated-resource/models/IReqDedicatedResourceState";
import IPaymentTypeState from "stores/payment-type/models/IPaymentTypeState";
import IModalFirstLevelState from "stores/modal/first-level/models/IModalFirstLevelState";
import IModalSecondLevelState from "stores/modal/second-level/models/IModalSecondLevelState";
import IModalThirdLevelState from "stores/modal/third-level/models/IModalThirdLevelState";
import IModalNoPaddingState from "stores/modal/no-padding/models/IModalNoPaddingState";
import IPMOSupportState from "stores/pmo-support/models/IPMOSupportState";
import IFunnelWarrantySLAState from "stores/funnel-warranty/models/IFunnelWarrantySLAState";
import IPOCRequirementState from "stores/funnel-poc-requirement/models/IPOCRequirementState";
import IServiceItemState from "stores/service-item/models/IServiceItemState";
import IFunnelCostState from "stores/funnel-cost/models/IInitState";
import IActionPlaNotesState from "stores/actionplan-notes/models/IActionPlaNotesState";
import ISummaryActionPlanState from "stores/summary-actionplan/models/ISummaryActionPlanState";
import ISoftwareState from "stores/software/models/ISoftwareState";
import ICompetitorState from "stores/competitor/models/ICompetitorState";
import IFunnelOpportunityState from "stores/funnel-opportunity/models/IFunnelState";
import ICompetitorProductState from "stores/competitor-product/models/ICompetitorProductState";
import IReportManagerState from "stores/report-manager/models/IReportManagerState";
import IGeneratedState from "stores/generated-form/models/IGeneratedState";
import IWhatsNewState from "stores/whats-new/models/IWhatsNewState";
import IFunnelSplit from "stores/funnel-split-performance/models/IFunnelPerformanceState";
import ICoverageHourState from "stores/coverage-hour/models/ICoverageHourState";
import IResponseResolutionState from "stores/response-resolution/models/IResponseResolutionState";
import IPreventiveScheduleState from "stores/preventive-schedule/models/IPreventiveScheduleState";
import IFunnelTopState from "stores/funnel-top/models/IFunnelTopState";
import ICommissionIndexState from "stores/commision-index/models/ICommissionIndexState";
import IButtonToggleState from "stores/funnel-sales-analyst/button-toggle/models/IButtonToggleState";
import IFunnelSalesAnalystState from "stores/funnel-sales-analyst/funnel-sa/models/IFunnelSalesAnalystState";
import IDelegationState from "stores/delegation/models/IDelegationState";
import ICustomerCredit from "stores/customer-credit-service/models/ICustomerCreditState";
import IQuotaState from "stores/quota/models/IQuotaState";
import IKpiDashboardState from "stores/kpi/kpi-dashboard/models/IKpiDashboardState";
import IKpiDataState from "stores/kpi/kpi-data/models/IKpiDataState";
import IKpiSettingState from "stores/kpi/kpi-setting/models/IKpiSettingState";
import IActivityReportProductState from "stores/activity-report-product/models/IActivityReportProductState";
import IActivityReportState from "stores/activity-report/models/IActivityReportState";
import IActivityReportCategoryState from "stores/activity-report-category/models/IActivityReportCategoryState";
import IActivityReportActivityInformationState from "stores/activity-report-activity-information/models/IActivityReportActivityInformationState";
import IActivityReportNotesState from "stores/activity-report-notes/models/IActivityReportNotesState";
import IActivityReportSuperiorReviewState from "stores/activity-report-superior-review/models/IActivityReportSuperiorReviewState";
import IActivityReportCustomerSignatureState from "stores/activity-report-customer-signature/models/IActivityReportCustomerSignatureState";
import IActivityReportTotalCustomerExperienceState from "stores/activity-report-total-customer-experience/models/IActivityReportTotalCustomerExperienceState";
import IActivityReportTicketInformationState from "stores/activity-report-ticket-information/models/IActivityReportTicketInformationState";
import IEmployeeFreelanceState from "stores/employee-freelance/models/IEmployeeFreelanceState";
import ICreditBillingState from "stores/main-cbv/models/ICreditBillingState";
import IEmployeeFreelancePermanentState from "stores/employee-freelance-permanent/models/IEmployeeFreelancePermanentState";
import IAWSCredentialState from "stores/aws-credential/models/IAWSCredentialState";
import IAWSBillingState from "stores/aws-billing/models/IAWSBillingState";
import PssState from "stores/pss/models/IPssState";
import PMOState from "stores/pmo/models/IPMOState";
import ConfigItemsState from "stores/config-items/models/IConfigItemsState";
import ProjectGundamState from "stores/project-gundam/models/IProjectGundamState";
import WorkListState from "stores/work-list/models/IWorkListState";
import TicketState from "stores/ticket/models/ITicketState";
import IDedicatedResourcesState from "stores/dedicated-resources/models/IDedicatedResourcesState";
import IActivityReportGroupingState from "stores/activity-report-grouping/models/IActivityReportGroupingState";
import IPresalesView from "stores/presales-view/models/IPresalesViewState";
import ICustomerSettingState from "stores/customer-setting/models/ICustomerState";
import ISalesAssignState from "stores/customer-sales/models/ISalesAssignState";
import ICustomerNameState from "stores/customer-name/models/ICustomerNameState";
import IBrandSummaryState from "stores/brand-summary/models/IBrandSummaryState";
import IServiceSummaryState from "stores/service-summary/models/IServiceSummaryState";
import IInvoicingScheduleState from "stores/invoicing-schedule/models/IInvoicingScheduleState";
import IInvoicingConditionState from "stores/invoicing-condition/models/IInvoicingConditionState";
import IRelatedCustomerState from "stores/related-customer/models/IRelatedCustomerState";
import IRelatedFileState from "stores/related-file/models/IRelatedFileState";
import IConfigItemState from "stores/config-item/models/ConfigItemState";
import ICollectionHistoryState from "stores/collection-history/models/CollectionHistoryState";
import IProjectHistoryState from "stores/project-history/models/IProjectHistoryState";
import ICollabToolsState from "stores/collab-tools/models/ICollabToolsState";
import ICustomerMasterState from "stores/customer-master/models/ICustomerMasterState";
//import NavState from 'stores/nav/models/INavState';

export default interface IStore {
  readonly error: IErrorState;
  readonly requesting: IRequestingState;
  readonly router: RouterState;
  readonly toasts: IToastsState;
  readonly modalFirstLevel: IModalFirstLevelState;
  readonly modalSecondLevel: IModalSecondLevelState;
  readonly modalThirdLevel: IModalThirdLevelState;
  readonly modalNoPadding: IModalNoPaddingState;
  readonly serviceCatalog: IServiceCatalogState;
  readonly serviceCatalogCategory: IServiceCatalogCategoryState;
  readonly customerTransfer: ICustomerTransferState;
  readonly historyTransfer: IHistoryState;
  readonly dataFunnel: IDataFunnelState;
  readonly dataFunnelCustomer: IDataFunnelCustomerState;
  readonly dataValue: IValueState;
  readonly employee: IEmployeeState;
  readonly customer: ICustomerState;
  readonly bondType: IBondTypeState;
  readonly language: ILanguageState;
  readonly bank: IBankState;
  readonly bondIssuer: IBondIssuerState;
  readonly letterType: ILetterTypeState;
  readonly documentType: IDocumentTypeState;
  readonly industryClass: IIndustryClassState;
  readonly presalesSupport: IPresalesSupportState;
  readonly serviceOwner: IServiceOwnerState;
  readonly brand: IBrandState;
  readonly subBrand: ISubBrandState;
  readonly brandModel: IBrandTypeState;
  readonly funnel: IFunnelState;
  readonly customerPIC: ICustomerPICState;
  readonly funnelProductService: IProductServiceState;
  readonly funnelActivity: IFunnelActivityState;
  readonly activityType: IActivityTypeState;
  readonly attachment: IAttachmentState;
  readonly attachmentVersions: IAttachmentVersionsState;
  readonly customerToFunnel: ICustomerToFunnelState;
  readonly meetingRequest: IMeetingRequestState;
  readonly sidebar: ISidebarContainerState;
  readonly meetingMomItems: IMeetingMomItemState;
  readonly meetingMom: IMeetingMomState;
  readonly funnelServiceCatalog: IFunnelServiceCatalogState;
  readonly funnelBoq: IBoqState;
  readonly insurance: IInsuranceModelState;
  readonly postsalesSupport: IPostsalesSupportState;
  readonly poc: IPOCState;
  readonly funnelStatus: IFunnelStatusState;
  readonly userLogin: IUserState;
  readonly presalesView: IPresalesView;
  readonly supportRole: ISupportRoleState;
  readonly funnelSupportTeams: IFunnelSupportTeamState;
  readonly bankGaransi: IBankGaransiState;
  readonly reqDedicatedResource: IReqDedicatedResourceState;
  readonly paymentType: IPaymentTypeState;
  readonly pmoSupport: IPMOSupportState;
  readonly funnelWarrantySLA: IFunnelWarrantySLAState;
  readonly pocRequirement: IPOCRequirementState;
  readonly actionPlan: IActionPlaNotesState;
  readonly summaryActionPlan: ISummaryActionPlanState;
  readonly serviceItem: IServiceItemState;
  readonly competitor: ICompetitorState;
  readonly costTable: IFunnelCostState;
  readonly reportManager: IReportManagerState;
  readonly software: ISoftwareState;
  readonly competitorProduct: ICompetitorProductState;
  readonly funnelOpportunity: IFunnelOpportunityState;
  readonly generatedForm: IGeneratedState;
  readonly whatsNew: IWhatsNewState;
  readonly funnelSplit: IFunnelSplit;
  readonly coverageHour: ICoverageHourState;
  readonly responseResolution: IResponseResolutionState;
  readonly preventiveSchedule: IPreventiveScheduleState;
  readonly funnelTop: IFunnelTopState;
  readonly commissionIndex: ICommissionIndexState;
  readonly buttonToggle: IButtonToggleState;
  readonly funnelSalesAnalyst: IFunnelSalesAnalystState;
  readonly delegation: IDelegationState;
  readonly customerCredit: ICustomerCredit;
  readonly quota: IQuotaState;
  readonly kpiDashboard: IKpiDashboardState;
  readonly kpiData: IKpiDataState;
  readonly kpiSetting: IKpiSettingState;
  readonly activityReport: IActivityReportState;
  readonly activityReportProduct: IActivityReportProductState;
  readonly activityReportCategory: IActivityReportCategoryState;
  readonly activityReportActivityInformation: IActivityReportActivityInformationState;
  readonly activityReportNotes: IActivityReportNotesState;
  readonly activityReportSuperiorReview: IActivityReportSuperiorReviewState;
  readonly activityReportCustomerSignature: IActivityReportCustomerSignatureState;
  readonly activityReportTotalCustomerExperience: IActivityReportTotalCustomerExperienceState;
  readonly activityReportTicketInformation: IActivityReportTicketInformationState;
  readonly activityReportGrouping: IActivityReportGroupingState;
  readonly employeeFreelance: IEmployeeFreelanceState;
  readonly employeeFreelancePermanent: IEmployeeFreelancePermanentState;
  readonly creditBilling: ICreditBillingState;
  readonly awsCredentital: IAWSCredentialState;
  readonly awsBilling: IAWSBillingState;
  readonly pss: PssState;
  readonly pmo: PMOState;
  readonly configItems: ConfigItemsState;
  readonly projectGundam: ProjectGundamState;
  readonly dedicatedresources: IDedicatedResourcesState;
  readonly workList: WorkListState;
  readonly ticket: TicketState;
  readonly customerSetting: ICustomerSettingState;
  readonly customerMaster: ICustomerMasterState;
  readonly customerSalesAssign: ISalesAssignState;
  readonly customerName: ICustomerNameState;
  readonly brandSummary: IBrandSummaryState;
  readonly serviceSummary: IServiceSummaryState;
  readonly invoicingSchedule: IInvoicingScheduleState;
  readonly invoicingCondition: IInvoicingConditionState;
  readonly relatedCustomer: IRelatedCustomerState;
  readonly relatedFile: IRelatedFileState;
  readonly configItem: IConfigItemState;
  readonly collectionHistory: ICollectionHistoryState;
  readonly projectHistory: IProjectHistoryState;
  readonly collabTools: ICollabToolsState;
  //readonly nav: NavState;
}
