import DedicatedResourcesEnvelope from './DedicatedResourcesEnvelope';
import ResultActions from 'models/ResultActions';
import DropdownDedicatedResourcesModel from './DropdownDedicatedResourcesModel';
import ListApprovalModel from './ListApprovalModel';
import GetEmployeeInfoModel from './DedicatedResourcesViewEdit/GetEmployeeInfoModel';
import GetEmployeeDetailModel from './DedicatedResourcesViewEdit/GetEmployeeDetailModel';
import DeductionsEnvelope from './DedicatedResourcesViewEdit/Deductions/DeductionsEnvelope';
import DeductionsModel from './DedicatedResourcesViewEdit/Deductions/DeductionsModel';
import GetProjectInfoModel from './DedicatedResourcesViewEdit/GetProjectInfoModel';
import OtherBenefitEnvelope from './DedicatedResourcesViewEdit/OtherBenefit/OtherBenefitEnvelope';
import SalaryBenefitEnvelope from './DedicatedResourcesViewEdit/SalaryBenefit/SalaryBenefitEnvelope';
import SalaryBenefitModel from './DedicatedResourcesViewEdit/SalaryBenefit/SalaryBenefitModel';
import SalaryBenefitModelById from './DedicatedResourcesViewEdit/SalaryBenefit/SalaryBenefitById';
import OtherBenefitTemplateProject from './DedicatedResourcesViewEdit/OtherBenefit/OtherBenefitTemplateProject';
import WorkFlowHeaderModel from './WorkFlowHeaderModel';
import VerificationDataStatusModel from './VerificationDataStatusModel';
import EmployeeModel from 'stores/employee/models/EmployeeModel';
import GetSearchSOOIModel from './DedicatedResourcesViewEdit/GetSearchSOOIModel';
import GetHistoryContractEnvelope from './GetHistoryContractEnvelope';
import GetActivityReportEnvelope from './GetActivityReportEnvelope';
import OtherBenefitLastContractEnvelope from './DedicatedResourcesViewEdit/OtherBenefit/OtherBenefitLastContractEnvelope';
import WorkFlowHeaderEnvelope from './WorkFlowHeaderEnvelope';
import DocumentTrackingModel from './DocumentTrackingModel';
import ResultCheck from './ResultCheck';

export default interface IDedicatedResourcesState {
  readonly listData: DedicatedResourcesEnvelope;
  readonly listDataBulkUpdate: DedicatedResourcesEnvelope;
  readonly listHistoryContract: GetHistoryContractEnvelope;
  readonly listActivityReport: GetActivityReportEnvelope;
  readonly listDeductions: DeductionsEnvelope;
  readonly listOtherBenefit: OtherBenefitEnvelope;
  readonly listSalaryBenefit: SalaryBenefitEnvelope;
  readonly listOtherLastContract: OtherBenefitLastContractEnvelope;
  readonly listOtherTemplateProject: OtherBenefitTemplateProject[];
  readonly DeductionById: DeductionsModel;
  readonly SalaryBenefitById: SalaryBenefitModelById;
  readonly DropdownContractStatus: DropdownDedicatedResourcesModel[];
  readonly DropdownDepartment: DropdownDedicatedResourcesModel[];
  readonly DropdownSupervisor: DropdownDedicatedResourcesModel[];
  readonly DropdownDeductionType: DropdownDedicatedResourcesModel[];
  readonly DropdownDeductionDesc: DropdownDedicatedResourcesModel[];
  readonly DropDownOtherBenefitType: DropdownDedicatedResourcesModel[];
  readonly DropDownOtherBenefitDesc: DropdownDedicatedResourcesModel[];
  readonly DropDownSalaryBenefitType: DropdownDedicatedResourcesModel[];
  readonly DropDownSalaryBenefitDesc: DropdownDedicatedResourcesModel[];
  readonly DropDownUMRYearSalaryBenefit: DropdownDedicatedResourcesModel[];
  readonly DropDownUMRSalaryBenefit: DropdownDedicatedResourcesModel[];
  readonly DropdownSenderAdmin: DropdownDedicatedResourcesModel[];
  readonly DropDownBuCost: DropdownDedicatedResourcesModel[];
  readonly DropdownEmployee: EmployeeModel[];
  readonly TakeHomePay: DropdownDedicatedResourcesModel;
  readonly CurrentSalary: DropdownDedicatedResourcesModel;
  readonly WorkFlowHeader: WorkFlowHeaderEnvelope;
  readonly ListApprovalButton: ListApprovalModel[];
  readonly VerificationDataStatus: VerificationDataStatusModel[];
  readonly SearchSOOI: GetSearchSOOIModel[];
  readonly EmployeeInfo: GetEmployeeInfoModel;
  readonly EmployeeDetail: GetEmployeeDetailModel;
  readonly ProjectInfo: GetProjectInfoModel;
  readonly DocumentTracking: DocumentTrackingModel;
  readonly CheckLastEmployeeContract: ResultCheck;
  readonly CheckSubmited: ResultCheck;
  readonly CheckApproval: ResultCheck;
  readonly error: boolean;
  readonly refreshPage: boolean;
  readonly resultActions: ResultActions;
  readonly isExportExcel: boolean;
}
